### ISSUE TITLE
Add time prettifier for UI display

### ISSUE THREAD

**Issue by darrenwee** [CS2103AUG2016-F11-C3/main#57]
Add `LocalDateTime` prettifier for UI display.

(assume it's 21 October 2016)
1. `2016-10-22T12:30` show up nicely as `Saturday, 12:30PM`
2. Need to deal with relative dates, e.g. `2016-10-28T18:30` should show as `Next Friday, 6:30PM`

**Comment by yyc** [comment]
Added, DTP has some issues that I wrote in #58
