### ISSUE TITLE
Relative times in ItemCard should update automatically

### ISSUE THREAD

**Issue by yyc** [CS2103AUG2016-F11-C3/main#62]
Right now they don't, because there's no easy and efficient way to update all of the itemcards at their respective intervals. One possible way is to modify the extractPrettyDateTime to also return an estimated interval to wait before the time should be checked again, and then make each Item check against that.
An alternative is to have a "ticking" observer of sorts as a static object in Item, and every Item observes this object and refreshes the datetime when it does. This is quite inefficient, but not too difficult to implement.

**Comment by darrenwee** [comment]
Is it possible to update all the item cards upon a UI event instead of relying on a ticker? e.g. whenever user types in an (in)valid command, user clicks on the item card, etc?

**Comment by yyc** [comment]
Deferred for v0.6
